### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by elwayman02** [cmanzana/node-publish#10]
I started receiving the following error upgrading from `0.5.0` to `0.6.0`:

```
/ember-tumblr/node_modules/publish/index.js:15
        callback(err, npm);
        ^

TypeError: callback is not a function
    at EventEmitter.<anonymous> (/ember-tumblr/node_modules/publish/index.js:15:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

The error is occurring [here](https://github.com/cmanzana/node-publish/blob/master/index.js#L15)

I'm wondering if it has to do with adding `tagName` as the first parameter? Or possibly something else broke to trigger the error?

Here's how I'm [using `publish`](https://github.com/elwayman02/ember-tumblr/blob/master/config/release.js)

**Comment by benhoIIand** [comment]
I ran into the same problem. The exposed API has been changed but the major version of the package was not bumped as it should have been if following semver. You can get around the problem by calling start with an empty string first `.start('', () => {})`
